theme = "catppuccin_mocha"

[editor]
scrolloff = 0
scroll-lines = 1
shell = ["zsh", "-c"]
line-number = "relative"
cursorline = true
auto-format = true
preview-completion-insert = false
completion-replace = false
rulers = [81]
bufferline = "always"
color-modes = true
true-color = true

[editor.lsp]
display-messages = true
auto-signature-help = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.smart-tab]
enable = false

[keys.normal]
g = { v = ["vsplit", "goto_definition"] }
y = "yank_to_clipboard"
Y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"

[keys.normal.space]
space = "file_picker"
z = ":sh zellij run --close-on-exit --direction right -- hx ."
x = ":sh zellij run --close-on-exit --floating -- xplr ."

[keys.select]
y = "yank_to_clipboard"
Y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"

[keys.insert]
"A-right" = "move_next_word_start"
"A-left" = "move_prev_word_start"
