############
# ESlint
############
[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

############
# Python
############
[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt"]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["pyright", "ruff"]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language-server.ruff]
command = "ruff-lsp"

[language.formatter]
command = "black"
args = ["--quiet", "-"]

############
# Rust
###########
[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
comment-token = "//"
language-servers = ["rust-analyzer"]
indent = { tab-width = 4, unit = "    " }

[language-server.rust-analyzer.config.check]
command = "clippy"

############
# Tailwindcss
############
[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

############
# TOML
############
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

############
# Typescript
###########
[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "(ts|typescript)"
file-types = ["ts", "mts", "cts"]
language-id = "typescript"
shebangs = ["deno", "ts-node"]
language-servers = [
  { except-features = [
    "format",
  ], name = "typescript-language-server" },
  "eslint",
]
indent = { tab-width = 2, unit = "  " }

############
# Vue
############
[[language]]
name = "vue"
scope = "source.vue"
injection-regex = "vue"
file-types = ["vue"]
roots = ["package.json"]
indent = { tab-width = 2, unit = "  " }
language-servers = [
  { except-features = [
    "format",
  ], name = "vuels" },
  "tailwindcss",
  "eslint",
]
