############
# C
###########
[[language]]
name = "c"
auto-format = true

############
# Markdown
############
[[language]]
name = "markdown"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'

############
# Python
############
[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt"]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["pyright", "ruff"]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language-server.ruff]
command = "ruff-lsp"

[language.formatter]
command = "black"
args = ["--quiet", "-"]

############
# Rust
###########
[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
comment-token = "//"
language-servers = ["rust-analyzer"]
indent = { tab-width = 4, unit = "    " }

[language-server.rust-analyzer.config.check]
command = "clippy"

############
# Tailwindcss
############
[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

############
# TOML
############
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

############
# Typescript
###########
[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
roots = [
  "package.json",
  "tsconfig.json",
  ".prettierrc.json",
  ".prettierrc",
  "eslint.config.js",
]
formatter = { command = 'prettier', args = ["--stdin-filepath", "file.ts"] }
auto-format = true

############
# Vue
############
[[language]]
name = "vue"
roots = [
  "package.json",
  "tsconfig.json",
  ".prettierrc.json",
  ".prettierrc",
  "tailwind.config.js",
  "eslint.config.js",
]
language-servers = ["vuels", "tailwindcss"]
formatter = { command = 'prettier', args = ["--stdin-filepath", "file.vue"] }
auto-format = true
