# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  # Fleet Dark-inspired theme for LazyGit
  theme:
    activeBorderColor:
      - '#268BD2' # Soft blue accent (similar to Helix/Zed's cursor highlight)
      - bold
    inactiveBorderColor:
      - '#333333' # Dark gray for inactive elements
    optionsTextColor:
      - '#6C8EDB' # Muted blue (used in Zed for text accents)
    selectedLineBgColor:
      - '#1F1F1F' # Very dark gray for selected line background
    cherryPickedCommitBgColor:
      - '#2C2C2C' # Slightly lighter dark gray for cherry-picked commits
    cherryPickedCommitFgColor:
      - '#A8CC7C' # Soft lime green for foreground, consistent with highlights
    unstagedChangesColor:
      - '#E394DC' # Pink for unstaged changes, keeping subtle vibrance
    defaultFgColor:
      - '#D1D1D1' # Light gray for default text color
    searchingActiveBorderColor:
      - '#F8AB17' # Yellow for search highlights (contrasting active borders)

  authorColors:
    '*': '#878EC0' # Muted lavender for author names, consistent with soft themes

